export const API_URL = 'https://norma.nomoreparties.space/api'

export const modalRoot = 'modal-root'
export const DragType = 'ingredient'
export const DragConstructorItemType = 'burger-ingredient'
export const IngredientTypes = {
  bun: 'bun',
  sauce: 'sauce',
  main: 'main',
} as const

export const ROUTES = {
  home: '/',
  login: '/login',
  register: '/register',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
  profile: '/profile',
  profileInfo: '/profile/info',
  profileOrders: '/profile/orders',
  feed: '/feed',
  feedOrder: '/feed/:feedId',
  ingredient: '/ingredients/:ingredientId',
  notFound: '*',
} as const

export const URLS = {
  login: '/auth/login',
  register: '/auth/register',
  token: '/auth/token',
  logout: '/auth/logout',
  user: '/auth/user',
  ingredients: '/ingredients',
  order: '/orders',
  passwordReset: '/password-reset',
  passwordResetSubmit: '/password-reset/reset',
} as const

export const MODE = {
  login: 'login',
  register: 'register',
  forgotPassword: 'forgotPassword',
  resetPassword: 'resetPassword',
} as const

export const OrderStatus = {
  PENDING: 'В ожидании',
  CANCELLED: 'Отменен',
  IN_PROGRESS: 'Готовится',
  DONE: 'Выполнен',
} as const

export const resetPasswordValidationSchema = {
  code: (value: string): string | null => (!value ? 'Code is required' : null),
  password: (value: string): string | null =>
    value.length < 6 ? 'Password must be at least 6 characters long' : null,
}

export const loginValidationSchema = {
  email: (value: string): string | null => (!value ? 'Email is required' : null),
  password: (value: string): string | null => (!value ? 'Password is required' : null),
}

export const registerValidationSchema = {
  email: (value: string): string | null => (!value ? 'Email is required' : null),
  password: (value: string): string | null =>
    value.length < 6 ? 'Password must be at least 6 characters long' : null,
  name: (value: string): string | null => (!value ? 'Name is required' : null),
}

export const forgotPasswordValidationSchema = {
  email: (value: string): string | null => (!value ? 'Email is required' : null),
}

export const orders = [
  {
    _id: '60d3b41abdacab0026a733c7',
    number: '034536',
    createdAt: '2024-12-11T12:59:00.000Z',
    name: 'Бессмертный оракул',
    status: 'done',
    ingredients: [
      {
        _id: '60d3b41abdacab0026a733c6',
        name: 'Краторная булка N-200i',
        type: IngredientTypes.bun,
        proteins: 80,
        fat: 24,
        carbohydrates: 53,
        calories: 420,
        price: 1255,
        image: 'https://code.s3.yandex.net/react/code/bun-02.png',
        image_mobile: 'https://code.s3.yandex.net/react/code/bun-02-mobile.png',
        image_large: 'https://code.s3.yandex.net/react/code/bun-02-large.png',
        __v: 0,
      },
      {
        _id: '60d3b41abdacab0026a733c5',
        name: 'Соус традиционный галактический',
        type: IngredientTypes.sauce,
        proteins: 42,
        fat: 24,
        carbohydrates: 42,
        calories: 99,
        price: 15,
        image: 'https://code.s3.yandex.net/react/code/sauce-03.png',
        image_mobile: 'https://code.s3.yandex.net/react/code/sauce-03-mobile.png',
        image_large: 'https://code.s3.yandex.net/react/code/sauce-03-large.png',
        __v: 0,
      },
      {
        _id: '60d3b41abdacab0026a733c5',
        name: 'Соус традиционный галактический',
        type: IngredientTypes.sauce,
        proteins: 42,
        fat: 24,
        carbohydrates: 42,
        calories: 99,
        price: 15,
        image: 'https://code.s3.yandex.net/react/code/sauce-03.png',
        image_mobile: 'https://code.s3.yandex.net/react/code/sauce-03-mobile.png',
        image_large: 'https://code.s3.yandex.net/react/code/sauce-03-large.png',
        __v: 0,
      },
      {
        _id: '60d3b41abdacab0026a733c5',
        name: 'Соус традиционный галактический',
        type: IngredientTypes.sauce,
        proteins: 42,
        fat: 24,
        carbohydrates: 42,
        calories: 99,
        price: 15,
        image: 'https://code.s3.yandex.net/react/code/sauce-03.png',
        image_mobile: 'https://code.s3.yandex.net/react/code/sauce-03-mobile.png',
        image_large: 'https://code.s3.yandex.net/react/code/sauce-03-large.png',
        __v: 0,
      },
      {
        _id: '60d3b41abdacab0026a733c5',
        name: 'Соус традиционный галактический',
        type: IngredientTypes.sauce,
        proteins: 42,
        fat: 24,
        carbohydrates: 42,
        calories: 99,
        price: 15,
        image: 'https://code.s3.yandex.net/react/code/sauce-03.png',
        image_mobile: 'https://code.s3.yandex.net/react/code/sauce-03-mobile.png',
        image_large: 'https://code.s3.yandex.net/react/code/sauce-03-large.png',
        __v: 0,
      },
      {
        _id: '60d3b41abdacab0026a733c5',
        name: 'Соус традиционный галактический',
        type: IngredientTypes.sauce,
        proteins: 42,
        fat: 24,
        carbohydrates: 42,
        calories: 99,
        price: 15,
        image: 'https://code.s3.yandex.net/react/code/sauce-03.png',
        image_mobile: 'https://code.s3.yandex.net/react/code/sauce-03-mobile.png',
        image_large: 'https://code.s3.yandex.net/react/code/sauce-03-large.png',
        __v: 0,
      },
      {
        _id: '60d3b41abdacab0026a733c5',
        name: 'Соус традиционный галактический',
        type: IngredientTypes.sauce,
        proteins: 42,
        fat: 24,
        carbohydrates: 42,
        calories: 99,
        price: 15,
        image: 'https://code.s3.yandex.net/react/code/sauce-03.png',
        image_mobile: 'https://code.s3.yandex.net/react/code/sauce-03-mobile.png',
        image_large: 'https://code.s3.yandex.net/react/code/sauce-03-large.png',
        __v: 0,
      },
      {
        _id: '60d3b41abdacab0026a733c5',
        name: 'Соус традиционный галактический',
        type: IngredientTypes.sauce,
        proteins: 42,
        fat: 24,
        carbohydrates: 42,
        calories: 99,
        price: 15,
        image: 'https://code.s3.yandex.net/react/code/sauce-03.png',
        image_mobile: 'https://code.s3.yandex.net/react/code/sauce-03-mobile.png',
        image_large: 'https://code.s3.yandex.net/react/code/sauce-03-large.png',
        __v: 0,
      },
      {
        _id: '60d3b41abdacab0026a733c5',
        name: 'Соус традиционный галактический',
        type: IngredientTypes.sauce,
        proteins: 42,
        fat: 24,
        carbohydrates: 42,
        calories: 99,
        price: 15,
        image: 'https://code.s3.yandex.net/react/code/sauce-03.png',
        image_mobile: 'https://code.s3.yandex.net/react/code/sauce-03-mobile.png',
        image_large: 'https://code.s3.yandex.net/react/code/sauce-03-large.png',
        __v: 0,
      },
    ],
  },
  {
    _id: '60d3b41abdacab0026a733c9',
    number: '034536',
    createdAt: '2024-12-10T12:59:00.000Z',
    name: 'Бессмертный оракул',
    status: 'done',
    ingredients: [
      {
        _id: '60d3b41abdacab0026a733c6',
        name: 'Краторная булка N-200i',
        type: IngredientTypes.bun,
        proteins: 80,
        fat: 24,
        carbohydrates: 53,
        calories: 420,
        price: 1255,
        image: 'https://code.s3.yandex.net/react/code/bun-02.png',
        image_mobile: 'https://code.s3.yandex.net/react/code/bun-02-mobile.png',
        image_large: 'https://code.s3.yandex.net/react/code/bun-02-large.png',
        __v: 0,
      },
      {
        _id: '60d3b41abdacab0026a733c5',
        name: 'Соус традиционный галактический',
        type: IngredientTypes.sauce,
        proteins: 42,
        fat: 24,
        carbohydrates: 42,
        calories: 99,
        price: 15,
        image: 'https://code.s3.yandex.net/react/code/sauce-03.png',
        image_mobile: 'https://code.s3.yandex.net/react/code/sauce-03-mobile.png',
        image_large: 'https://code.s3.yandex.net/react/code/sauce-03-large.png',
        __v: 0,
      },
    ],
  },
  {
    _id: '60d3b41abdacab0026a733c10',
    number: '034536',
    createdAt: '2024-11-25T12:59:00.000Z',
    name: 'Бессмертный оракул',
    status: 'done',
    ingredients: [
      {
        _id: '60d3b41abdacab0026a733c6',
        name: 'Краторная булка N-200i',
        type: IngredientTypes.bun,
        proteins: 80,
        fat: 24,
        carbohydrates: 53,
        calories: 420,
        price: 1255,
        image: 'https://code.s3.yandex.net/react/code/bun-02.png',
        image_mobile: 'https://code.s3.yandex.net/react/code/bun-02-mobile.png',
        image_large: 'https://code.s3.yandex.net/react/code/bun-02-large.png',
        __v: 0,
      },
      {
        _id: '60d3b41abdacab0026a733c5',
        name: 'Соус традиционный галактический',
        type: IngredientTypes.sauce,
        proteins: 42,
        fat: 24,
        carbohydrates: 42,
        calories: 99,
        price: 15,
        image: 'https://code.s3.yandex.net/react/code/sauce-03.png',
        image_mobile: 'https://code.s3.yandex.net/react/code/sauce-03-mobile.png',
        image_large: 'https://code.s3.yandex.net/react/code/sauce-03-large.png',
        __v: 0,
      },
    ],
  },
  {
    _id: '60d3b41abdacab0026a733c10',
    number: '034537',
    createdAt: '2024-12-10T12:59:00.000Z',
    name: 'Бессмертный оракул',
    status: 'done',
    ingredients: [
      {
        _id: '60d3b41abdacab0026a733c6',
        name: 'Краторная булка N-200i',
        type: IngredientTypes.bun,
        proteins: 80,
        fat: 24,
        carbohydrates: 53,
        calories: 420,
        price: 1255,
        image: 'https://code.s3.yandex.net/react/code/bun-02.png',
        image_mobile: 'https://code.s3.yandex.net/react/code/bun-02-mobile.png',
        image_large: 'https://code.s3.yandex.net/react/code/bun-02-large.png',
        __v: 0,
      },
      {
        _id: '60d3b41abdacab0026a733c5',
        name: 'Соус традиционный галактический',
        type: IngredientTypes.sauce,
        proteins: 42,
        fat: 24,
        carbohydrates: 42,
        calories: 99,
        price: 15,
        image: 'https://code.s3.yandex.net/react/code/sauce-03.png',
        image_mobile: 'https://code.s3.yandex.net/react/code/sauce-03-mobile.png',
        image_large: 'https://code.s3.yandex.net/react/code/sauce-03-large.png',
        __v: 0,
      },
    ],
  },
]
